---
name: AIS-catcher
version: edge
slug: aiscatcher
description: AIS-catcher Add-on for Homeassistant
url: https://github.com/kb-light/hassio-ais-catcher.git
arch: 
  - amd64
ports:
  8110/tcp: 8110
  8100/tcp: 8100
ports_description:
  8110/tcp: AIS-catcher config
  8100/tcp: AIS-catcher webview
devices:
  - /dev/bus/usb:/dev/bus/usb
image: ghcr.io/jvde-github/ais-catcher-control
